//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferreteria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_venta
    {
        public int id_detalle_venta { get; set; }
        public string cod_detalle_venta { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_venta { get; set; }
        public Nullable<int> total { get; set; }
        public string nombre_usuario { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual venta venta { get; set; }
    }
}
