//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferreteria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.venta = new HashSet<venta>();
        }
    
        public string codigo_usuario { get; set; }
        public string rut_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public Nullable<int> id_tipo_usuario { get; set; }
        public string clave { get; set; }
    
        public virtual tipo_usuario tipo_usuario { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
